import type { Metadata } from "next";
import { SidebarProvider } from "@/components/shadcn/ui/sidebar";
import { AppSidebar } from "@/components/shadcn/app-sidebar";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";
import ReactQueryProvider from "@/utils/providers/react-query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <SidebarProvider>
            <div className="flex w-full">
              <AppSidebar />
              <div className="flex flex-col grow">
                <header>
                  <Header />
                </header>
                <main className="bg-background min-h-[calc(100vh-75px)] px-8 py-8">
                  {children}
                </main>
              </div>
            </div>
          </SidebarProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
